GET http://localhost:8080/AddressBook/hello/contacts?nameFilter=^[AB]

###
GET http://localhost:8080/AddressBook/hello/contacts?nameFilter=^.*[aeiy].*$

###
GET 192.168.88.251:8080/AddressBookService/hello/contacts?nameFilter=^.*[aey].*$